### ISSUE TITLE
6.0.0.alpha.9: rebuild error in android studio

### ISSUE THREAD

**Issue by emclab** [mCodex/react-native-sensitive-info#279]
My RN 0.64 app upgrades the module to 6.0.0.alpha.9 and it throws error when rebuild in android studio (4.1.13). Here is the error:

      C:\D\code\js\xyz_app4\node_modules\react-native-sensitive-info\android\src\main\java\dev\mcodex\RNSensitiveInfoModule.java:385: error: cannot find symbol
        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.N) {
                                                        ^
        symbol:   variable N
        location: class VERSION_CODES
      C:\D\code\js\xyz_app4\node_modules\react-native-sensitive-info\android\src\main\java\dev\mcodex\RNSensitiveInfoModule.java:387: error: cannot find symbol
                builder.setInvalidatedByBiometricEnrollment(invalidateEnrollment);
                       ^
        symbol:   method setInvalidatedByBiometricEnrollment(boolean)
        location: variable builder of type Builder
      C:\D\code\js\xyz_app4\node_modules\react-native-sensitive-info\android\src\main\java\dev\mcodex   \RNSensitiveInfoModule.java:
      uses or overrides a deprecated API.
      Recompile with -Xlint:deprecation for details.

The `yarn android` throws error as well.

**Comment by emclab** [comment]
After increase the android sdk version and min sdk targeted, the error disappeared.

**Comment by emclab** [comment]
![Capture](https://user-images.githubusercontent.com/946013/114781916-2f25e080-9d2e-11eb-8c6f-c59a75474266.JPG)
