### ISSUE TITLE
"Error storing data" on keystore branch

### ISSUE THREAD

**Issue by wanderSX** [mCodex/react-native-sensitive-info#123]
After #120 I'm getting error on keystore branch

> ExceptionsManager.js:84 Error storing data Error: Attempt to invoke virtual method 'javax.crypto.SecretKey java.security.KeyStore$SecretKeyEntry.getSecretKey()' on a null object reference

"react-native": "0.57.0"
"redux-persist": "^5.10.0",
"redux-persist-sensitive-storage": "^1.0.0",

**Comment by jordoh** [comment]
I'm seeing the same exception after updating from 99d010b144df258abb87facf0a81ef4a02f5ec9f to 38b9011bddea5c583a54c81d2a17430cfa4c1a98 then uninstalling + re-installing the application. Running the app with the updated code prior to re-installing did not result in an exception. 863d3e9cef8bdb2bd93c763cf439ae1944bae944 seems to be the most likely culprit, since it touched this code and was not included in the previous version I was using.

This happens when calling `await SInfo.setItem(key, value, options)` - `key` and `value` are both non-empty strings. `options` has the `sharedPreferencesName` and `keychainService` entries. I'm able to call `getItem`, though it does not have a value stored for the key I'm using (hence my updating to the latest keystore branch, to get #120).

I've observed this on an API 27 Android 8.1 emulator instance and a Pixel 2 device running Android 9.

**Comment by wanderSX** [comment]
@star-collector 
Can't tell exactly which method caused it, because i'm not using it directly from my code. redux-persist-sensitive-storage is using this lib to store data with redux-persist.

Re-installing node_modules and app itself did not help.

Galaxy S8 with Android 8.0.

**Comment by star-collector** [comment]
Ok, I think I found out what caused the problem. Just as I thought #120 wasn't the culprit. The bug appeared only on Android >= 8.0 devices. For some reason key generator didn't create instance with RSA encryption, so obviously secret key's retrieval failed.

I made a pull request with the fix for this issue: #126

**Comment by mCodex** [comment]
Thanks @star-collector, I've merged your PR :)
