### ISSUE TITLE
Androidx Support

### ISSUE THREAD

**Issue by ErnesII** [mCodex/react-native-sensitive-info#156]
It seems that this library is not working with rn 0.60, so I just changed this import: 
import android.support.annotation.NonNull; by this import androidx.annotation.NonNull;

Im creating this issue for someone that is having problem with this library and rn 0.60. It is a temporal fix.

react-native-sensitive-info ->  android -> build -> src -> main -> java -> br -> com -> classmap -> RNSensitiveInfo -> RNSensitiveInfoModule.java

**Comment by bneigher** [comment]
+1

**Comment by Cyrxio** [comment]
I made a PR for this : #157 
Need it too.

**Comment by mCodex** [comment]
Released in 5.5.0 👍

**Comment by jacek213** [comment]
@mCodex 

With this change and RN 0.59.10 I'm unable to build app.

Getting this error:

`node_modules/react-native-sensitive-info/android/src/main/java/br/com/classapp/RNSensitiveInfo/RNSensitiveInfoModule.java:18: error: cannot find symbol
import androidx.annotation.NonNull;
`

**Comment by mCodex** [comment]
@jacek213 can you try to use 5.4.x, because v5.5.0 is only for RN 0.60+ 🤗

**Comment by jacek213** [comment]
yup I did so yesterday, thx for the reply :)

**Comment by michalpilarekfrisco** [comment]
Could You make same changes for KeyStore branch?

**Comment by aliceathens** [comment]
+1
